export enum Mutations {
  SET_SETTINGS = 'SET_SETTINGS',
  SET_WELCOME_MESSAGE_SHOWN = 'SET_WELCOME_MESSAGE_SHOWN',
  UPDATE_CHANGELOG_BUILD_DETAILS = 'UPDATE_CHANGELOG_BUILD_DETAILS',
  UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS',
}
